# Generated by Django 2.1.5 on 2019-06-06 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fatalgram.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('photo_taken', models.DateTimeField(blank=True, null=True)),
                ('photo_camera', models.CharField(max_length=200, null=True)),
                ('photo_lat', models.CharField(max_length=200, null=True)),
                ('photo_lon', models.CharField(max_length=200, null=True)),
                ('photo_alt', models.CharField(max_length=200, null=True)),
                ('photo_raw', models.ImageField(upload_to=fatalgram.models.path_raw)),
                ('photo_thumb', models.ImageField(upload_to=fatalgram.models.path_thumb)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
