# Generated by Django 2.1.5 on 2019-06-06 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fatalgram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('trip_start', models.DateField(blank=True, null=True)),
                ('trip_end', models.DateField(blank=True, null=True)),
                ('summary', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fatalgram.Trip'),
        ),
    ]
