# Generated by Django 2.2.2 on 2019-09-02 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merossuser', models.CharField(max_length=50)),
                ('merosspassword', models.CharField(max_length=50)),
                ('buttonsecret', models.CharField(max_length=50)),
                ('webhookonurl', models.CharField(max_length=50)),
                ('webhookoffurl', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
